#!/bin/sh
##
##  claude-statusline launcher
##

self="$0"
while [ -L "$self" ]; do
    target=$(readlink "$self")
    case "$target" in
        /* ) self="$target" ;;
        *  ) self="$(dirname "$self")/$target" ;;
    esac
done
basedir=$(cd "$(dirname "$self")" && pwd)

exec node "$basedir/claude-statusline.js" "$@"

