#!/bin/sh
##
##  claudeX -- Claude Code eXtended
##  Copyright (c) 2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under GPL 3.0 <https://spdx.org/licenses/GPL-3.0-only>
##

if [ ".$CLAUDEX_BASEDIR" != . ]; then
    PATH="$CLAUDEX_BASEDIR:$PATH"
fi

exec claudex ${1+"$@"}

