#!/bin/sh
if [ ".$CLAUDEX" != . ]; then
    PATH="$CLAUDEX:$PATH"
fi
host=""
if [ $# -ge 1 ] && [ ".$1" = ".-h" ]; then
    shift
    host="-h"
fi
if [ ".$1" = .session ]; then
    shift
    exec claudex $host session ${1+"$@"}
else
    exec claudex $host naked ${1+"$@"}
fi
