#!/bin/sh
if [ ".$CLAUDEX" != . ]; then
    PATH="$CLAUDEX:$PATH"
fi
sandbox=""
if [ $# -ge 1 ] && [ ".$1" = ".-s" ]; then
    shift
    sandbox="-s"
fi
if [ ".$1" = .session ]; then
    shift
    exec claudex $sandbox session ${1+"$@"}
else
    exec claudex $sandbox naked ${1+"$@"}
fi
