##
##  claudeX -- Claude Code eXtended
##  Copyright (c) 2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under GPL 3.0 <https://spdx.org/licenses/GPL-3.0-only>
##

#   build entire project
build
    eslint --config eslint.mjs claudex.ts && \
    tsc --project tsconfig.json

#   publish to github.com and npmjs.com
publish [hostname=en4.*]
    increment="patch"; \
    case "$*" in -i* ) increment=`echo "$*" | sed -e 's;^-i;;'` ;; esac; \
    kickout "$increment" && \
    VERSION=`sed -n '/"version":/ s/.*: *"\(.*\)".*/\1/p' package.json` && \
    V=`echo "$VERSION" | sed -e 's;\.;\\.;g'` && \
    sed -n -e "/^${V} /, /^[0-9]\\./ { /^${V} /p; /^[0-9]\\./!p; }" <CHANGELOG.md >.notes.md && \
    gh release create --title "claudeX $VERSION" --notes-file .notes.md --verify-tag $VERSION && \
    rm -f .notes.md

#   remove regularly built files
clean
    shx rm -f claudex.js tsc.tsbuildinfo

#   remove all built files
clean-dist : clean
    shx rm -f package-lock.json
    shx rm -rf node_modules

