##
##  claudeX -- Claude Code eXtended
##  Copyright (c) 2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under MIT <https://spdx.org/licenses/MIT>
##

#   build entire project
build
    eslint --config eslint.mjs claudex.ts
    tsc

#   remove regularly built files
clean
    shx rm -f claudex.js tsc.tsbuildinfo

#   remove all built files
clean-dist : clean
    shx rm -f package-lock.json
    shx rm -rf node_modules

