##
##  claudeX -- Claude Code eXtended
##  Copyright (c) 2026 Dr. Ralf S. Engelschall <rse@engelschall.com>
##  Licensed under GPL 3.0 <https://spdx.org/licenses/GPL-3.0-only>
##

#   build entire project
build
    eslint --config eslint.mjs claudex.ts && \
    tsc --project tsconfig.json

#   remove regularly built files
clean
    shx rm -f claudex.js tsc.tsbuildinfo

#   remove all built files
clean-dist : clean
    shx rm -f package-lock.json
    shx rm -rf node_modules

